### ISSUE TITLE
Idea: Render current source to images to compare with scans

### ISSUE THREAD

**Issue by Emyr42** [chrislgarry/Apollo-11#118]
Steps:

1. Create font which approximates the text produced by the original printers
2. Create texture generator which approximates the non-text patterns (paper colouring, repeated printer artefacts etc
3. ???
4. Profit!

Seriously though, are we at a point where rendering the current known source to "fake scans" might allow transcription errors to be highlighted?

**Comment by wopian** [comment]
The problem here is that the digitalised files have slightly different formatting. 

Besides having to create/find the font used, you'd need to strip the `#` in front of the comments and roughly space out the text so they're around the same location. Once converted to images, they'd need to be manually repositioned to match the offset and angle of the source images. 

In the end, I just see it taking far more effort and time than comparing the files to the images - since there's nearly 3500 pages.

**Comment by hatefkasraei** [comment]
or be a hero and read them with your eyes :D

**Comment by fireflyhoo** [comment]
who can change to golang

**Comment by chrislgarry** [comment]
What @wopian said. Thanks for the suggestion though. We may actually have more luck if we did OCR on the original scans to get digitization that way, but there are some parts that are simply washed out. It'd be much more work.
