### ISSUE TITLE
Fork as community effort?

### ISSUE THREAD

**Issue by johannesx75** [chrislgarry/Apollo-11#20]
The original project does not seem to be actively maintained by its creators. I could not find any indication of the code being used or updated since 1972. (Ok, some people doubt that it has ever been used, since the whole thing was staged.)

May I suggest that we fork the project as a community effort? Maybe we can get it back up and running.

**Comment by indy91** [comment]
All joking aside, the code is very much running in an emulator already. That's where this code is originally from: https://github.com/rburkey2005/virtualagc

And I am part of a development team that has implemented this AGC emulator in the simulated environment of the Orbit Space Flight Simulator. Here our project: https://github.com/dseagrav/NASSP

At this point we have a fully implemented and functional Command Module Computer with simulated IMU, optical subsystem etc. so that you can actually use the Virtual AGC.

**Comment by chrislgarry** [comment]
@indy91 that's awesome! Will Orbiter space flight simulator simulate all manned missions, past and upcoming?

**Comment by indy91** [comment]
@chrislgarry Well, Orbiter itself has only a limited number of spacecraft, but there is an active community of addon developers working on Apollo, Space Shuttle and other spacecraft.

For Apollo there are two addons for Orbiter. One is called AMSO and is not a detailed simulation, but it looks great and it already supports all missions of the Apollo program.

NASSP is currently mostly limited by an unfinished Lunar Module simulation, but the CSM is in a very advanced state, so that the two missions without the LM, Apollo 7 and 8, can already be flown from launch to splashdown, including the Virtual AGC. As an example, here a quick demonstration video I made: https://www.youtube.com/watch?v=fjAeBJrsj5Q The video shows the reentry controlled by the Virtual AGC. Probably difficult to tell what is happening for people unfamiliar with the project, but it's the AGC emulator in control.

There are already testing scenarios for the later Apollo missions, including an Apollo 11 scenario that runs exactly the code in this repository, CSM and LM. You can take it to lunar orbit, but not all the way to the surface yet. NASSP comes with all the different versions of the AGC and Abort Guidance System that the Virtual AGC project provides, but it's not all implemented yet. It's just a few people working on it, so it will probably still take quite a while until we can actually let the Virtual AGC fly lunar landings.
