### ISSUE TITLE
[language agnostic] needs more directories

### ISSUE THREAD

**Issue by hoosierEE** [chrislgarry/Apollo-11#21]
It's very disturbing to be able to see all the source code completely exposed in the top-level directory.

Suggest restructuring the code to follow modern best practices of hierarchical/modular folder and file organization, such as [this prime example](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition).

**Comment by thepauleh** [comment]
Jesus, Alex. Really want to live on the seat of your pants don't you?

Trying to push through these insane concepts again??. Directories, you say now? If the Russians beat us to the moon due to this radical new fangled concept we'll all be hanged for treason.

This outburst is going on your permanent file, comrade. Best you leave the big-thinking to those above your pay grade from now on.

**Comment by hoosierEE** [comment]
On second thought, having all the source code files in one directory is kind of nice.
