### ISSUE TITLE
Error 1201 and 1202 if rendezvous radar is turned on.

### ISSUE THREAD

**Issue by osresearch** [chrislgarry/Apollo-11#23]
The AGC reboots with a program code 1201 and 1202 ("Executive overflow") during landing phase if the rendezvous radar switch it set to AUTO (as suggested in procedure book) and the DELTAH command (1668) is initiated on the DSKY.  Bales in Guidance and Garman say it is ok to land with this error, but flight is still concerned about it and the alarms might distract the crew.

**Comment by osresearch** [comment]
The Apollo 11 [Flight plan](https://www.hq.nasa.gov/alsj/a11/a11fltpln_final_reformat.pdf) clearly indicates "RR ON" durng landing phase. Either the documentation and training should be updated or the 6400 cycles allocated to the rendezvous radar processing.

![image](https://cloud.githubusercontent.com/assets/3068843/16692918/e7e01c98-4500-11e6-9776-a8f0c4e3e6f8.png)

**Comment by mhenstell** [comment]
I don't think allocating more time to processing will fix the underlying problem. The PSUs for the CDU and the ATCA should really be in phase lock, or any random phase-misalignment could cause spurious interrupts.

**Comment by 7203200** [comment]
Wow，it's really good，I am from China，nice to meet you.
                                                                                                                           Fan Daoyu

**Comment by rietta** [comment]
I just sent a link to this issue to @TheRealBuzz on Twitter. Hopefully Dr. Aldrin can shed light on this given is experience working with AGC during the mission.

**Comment by chrislgarry** [comment]
**RR**: `Rendezvous Radar. A radar system for tracking where the command module is. This is not used during descent, but was on in case they needed to quickly ascend to the command module.`

**ATCA**: `Attitude and Translation Control Assembly. One of the main assemblies for controlling the lunar module. It controls the thrusters for attitude and translation, receiving input from either the joystick controllers (if in ABORT/manual control mode) or directly from the guidance computer's digital auto pilot if RR is engaged.`

**LGC**: `Lunar Module Guidance Computer. The main software system for the lunar module.`

**CDU**: `Coupling Data Unit. Tells the position of the radar antenna to the Lunar Guidance Computer software. It functions as an ADC, converting analog signals from the radar's sensors to digital signals for LGC.`

The bug is due to an inconsistency between where the CDU thinks the RR antenna is and where ATCA thinks expects it to be. It can be triggered whenever the RR is on (set to AUTO or SLEW). By design, the CDU relies on the phase of ATCA power supply to be in phase with its own to infer the position of the antenna. You can see in the diagram they use separate power sources and only perform frequency syncs, leaving the system vulnerable to undesired phase shifts that result in inaccurate position measurements if using the power supply as a base reference. Phase locking of these power supplies will ensure there is no phase difference, and thus no measurement discrepancy, which will avoid software interrupts being sent back to LGC from the CDU.
![pgns-atca](https://cloud.githubusercontent.com/assets/2200898/16712358/32a247c6-4653-11e6-89a6-c0e5be6c5e46.jpg)
