### ISSUE TITLE
Proof STABLE_ORBIT

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#258]
Proof read transcribed code of [STABLE_ORBIT](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/STABLE_ORBIT.agc) against scans

Lines: 429
Page: 0525—0532

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by Feliix42** [comment]
I'm currently working on this one. But the question is: Is it `GOTOPOOH` (7 occurrences throughout the repository) or `GOTOP00H` (199 occurrences throughout the repository)?

**Comment by victorleblais** [comment]
@Feliix42 I'm pretty sure it's `GOTOPOOH`.

If you look closely, the O is wider and more "square-shaped" than a zero. Compare `GOTO` and any number such as `00748` (on page 527). If needed, I can provide a close-up comparison of both characters.

**Comment by Feliix42** [comment]
This is exactly what I thought, but apparently all previous readers thought that it's `GOTOP00H` (~200 occurrences vs. 7).

So what now? One huge PR that fixes this?

**Comment by victorleblais** [comment]
I guess. Most (if not all?) occurences of `GOTOP00H` are there since the initial commits. It's very likely it's an error from the OCR since both characters are incredibly similar to one another.

I've cloned the commit [dc4ea67](https://github.com/chrislgarry/Apollo-11/tree/dc4ea6735c464608d704fa183f3e3d08b013c42f), one of the earliest ones, and with a quick cat/grep, there's 180+ lines containing `GOTOP00H` and 5 containing `GOTOPOOH`, despite both of them being used similarly ("TERMINATE"). So the amount of each is pretty similar since the beginning.

But there are occurences of multiple comments saying `GOTOPOOH --> GOTOP00H` and `GOTOP00H --> GOTOPOOH`, that bit confused me.

**Comment by wopian** [comment]
It's supposed to be `POOH`. It was fixed late last year in [Virtual AGC](https://github.com/virtualagc/virtualagc/blob/58aa21b8621ca7d9eb162729d7f74b613e900992/LUM99R2/P30%2CP37.agc#L16).

`VNP00H` is another that should be `VNPOOH` (well everything `**P00H`)

**Comment by Feliix42** [comment]
So are we opening another issue for the `**P00H`-> `**POOH` thing? (I would have to fix it for `STABLE_ORBIT.agc` too, I guess).
