### ISSUE TITLE
Commits with valid authors and dates...

### ISSUE THREAD

**Issue by lyda** [chrislgarry/Apollo-11#62]
Just curious, is it possible to try and approximate the original authors and commit dates using things like [GIT_AUTHOR_NAME](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) and so forth. And possibly using tags to note how the code looked at each launch. I'm not clear on what data on this might be available.

**Comment by chrislgarry** [comment]
That would be amazing. We would have to go through every source scan. Just to give you an idea of the magnitude of this sort of project, here are the scans for the lunar module: http://www.ibiblio.org/apollo/listings/Luminary099/. I tried doing some OCR on one of the scans, and it did not fair well out of the box. It'll require some fine-tuning for this.

**Comment by ilovemysillybanana** [comment]
Is that even possible? I didn't think they had version control software back then

**Comment by Palmitoxico** [comment]
I think it wouldn't be possible, as the development dates before 1st January of 1970 (Unix Time).

**Comment by masukomi** [comment]
also, if you could go through and do that you would screw up EVERY clone of this repo. Never rewrite public history.

**Comment by ohommes** [comment]
Why even set this repo up when all is available at: 
https://github.com/rburkey2005/virtualagc

Why not contribute to the historical skunk works that has been done since 2003 and continue to contribute to Ron Burkey's work. It is the single place where we have pulled together all the historical material. I have travelled and talked with many of the original developers and had them agree to mail their attic material to us. The project has been going on for years and has been collecting the sources of many flights for both CM and LM. With http://www.ibiblio.org/apollo/ being the official project front and the github for the public contributions.

**Comment by steve1780** [comment]
Onno is right. The official project at  http://www.ibiblio.org/apollo/ should be the official sourcebook and guide for all things AGC. Besides, if examining the source code for done for historical or educational purposes, you cannot understand the complexities of the AGC system with just the source code alone.

**Comment by chrislgarry** [comment]
@ohommes I think @lyda want's a repo that would look as if the original developers were using it as their repository. More of like a modern take on how the original developers would have used source control. @lyda if you're interested in this, @ohommes has linked to all the information you would need.
