### ISSUE TITLE
External temp shows reading for soundstage, not "space".

### ISSUE THREAD

**Issue by thesandbender** [chrislgarry/Apollo-11#63]
Mr. Kubrik pointed out that the external temperature gauge is showing the temperature for the sound stage.

**Comment by thesandbender** [comment]
Thanks for being a good sport about it (seriously) and thanks for taking the time to upload the code.  Jokes aside it's an important part of history and it's cool people can look over it.

**Comment by chrislgarry** [comment]
@thesandbender The joke issues just keep pouring in, but I enjoy reading them. There are real issues however, since [some source code is missing](https://github.com/chrislgarry/Apollo-11/issues/38), and there is now an effort to fix all the typos introduced from digitization of the original source. I'm just glad there's as much excitement about it as when I first found the source code online, thanks to Ron's effort with Virtual AGC.
