### ISSUE TITLE
Proof STABLE_ORBIT

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#640]
Proof read transcribed code of [STABLE_ORBIT](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/STABLE_ORBIT.agc) against scans

Lines: 441
Page: 0723—0730 (7)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by Sid200** [comment]
Hey @wopian! I am new here... Can I take this one?

**Comment by wopian** [comment]
@Gaboso go ahead! 👍

**Comment by Sid200** [comment]
Uhh

**Comment by wopian** [comment]
Oops

**Comment by Sid200** [comment]
Alrighty thanks!

**Comment by Sid200** [comment]
Hey, I am done checking. There were some line break issues, two hyphens instead of one in the comments and a date was wrong. There's just one error I am not sure of. Is this line in 0726.jpg:

![image](https://user-images.githubusercontent.com/41021075/83941982-5dcd5380-a80d-11ea-92ef-2a05f30131b3.png)

supposed to be a decimal point or a comma?

**Comment by wopian** [comment]
@Sid200 It's a decimal point.

**Comment by Sid200** [comment]
Ok I am done checking. Here are the corrections:

- Changed the double hyphens with a single one as per the scans.
- Changed the date from `26JAN68` to `25JAN68`
- Changed a comma to a decimal point. (`7,1` to `7.1`)
- Removed extra line breaks.

Opened a pull request.
